
// Generated by Cadence Encounter(R) RTL Compiler v14.10-s022_1

// Verification Directory fv/driver 

module driver(data_en, data_in, data_out);
  input data_en;
  input [7:0] data_in;
  output [7:0] data_out;
  
  assign data_out = data_en ? data_in : 0;
  
 endmodule

